# Optional file for deploying to Google App Engine Flexible Environment.
runtime: aspnetcore
env: flex

env_variables:
    DB_USER: <your-username>
    DB_PASS: <your-password>
    DB_NAME: <your-database-name>
    DB_HOST: cloudsql

beta_settings:
    cloud_sql_instances: "<project-name>:<region>:<instance-name>=tcp:5432"